### PR TITLE
Register TimestampConverter in DebeziumLogicalConverters

### PR DESCRIPTION
**Pull request by bingqinzhou**
Currently fields with the type of `io.debezium.time.Timestamps` are not converted into `TIMESTAMP` in BigQuery, but remains as `INTEGER` instead. This PR is a small patch to register TimestampConverter in DebeziumLogicalConverters.

### CODE REVIEW

**Comment by bingqinzhou** [comment]
It seems that I don't have access to add any reviewers. @C0urante @mtagle Can you please help review this small PR when you get a chance please? Thank you!

**Comment by C0urante** [comment]
Thanks @bingqinzhou. Could we add a unit test for this in the `DebeziumLogicalConvertersTest` class?

**Comment by bingqinzhou** [comment]
> Thanks @bingqinzhou. Could we add a unit test for this in the `DebeziumLogicalConvertersTest` class?

Hi @C0urante, thank you for taking a look! I think the unit test for TimestampConverter already exists in https://github.com/confluentinc/kafka-connect-bigquery/blob/master/kcbq-connector/src/test/java/com/wepay/kafka/connect/bigquery/convert/logicaltype/DebeziumLogicalConvertersTest.java#L111

**Comment by C0urante** [comment]
Ah, I see. Sorry about that @bingqinzhou, this is a simpler bug than I thought. Can you retarget `1.6.x` with your fix? We'll automatically propagate the fix from there through 2.0.x, 2.1.x, etc. to master.

**Review by C0urante — APPROVED** [review]
LGTM, can merge as soon as the target branch is changed to 1.6.x.

**Comment by bingqinzhou** [comment]
> Ah, I see. Sorry about that @bingqinzhou, this is a simpler bug than I thought. Can you retarget `1.6.x` with your fix? We'll automatically propagate the fix from there through 2.0.x, 2.1.x, etc. to master.

Hi @C0urante, I'm not sure how to retarget `1.6.x` with my fix. I didn't target this PR when I created actually. Do I just need to rebase this PR please?

**Comment by C0urante** [comment]
@bingqinzhou a rebase may be necessary, but to start with you can just change the target branch from `master` to `1.6.x` in the GitHub UI.

**Comment by bingqinzhou** [comment]
> @bingqinzhou a rebase may be necessary, but to start with you can just change the target branch from `master` to `1.6.x` in the GitHub UI.

@C0urante Got it, changed this PR to be based on `1.6.x`

**Comment by bingqinzhou** [comment]
Hi @C0urante, can you help me merge this PR if it looks good to you please? If there's anything I still need to do with this PR, please let me know soon, thanks!

**Comment by bingqinzhou** [comment]
> Hi @bingqinzhou--sorry, it looks like the retarget to 1.6.x has brought along all of the commits between 1.6.x and master, which we don't want to merge into master. Instead, we just want to merge your commit. Could you cherry-pick your commit onto 1.6.x, then force-push that branch to your `fix_timestamp_converter` branch?
> 
> If this is too much work I'm happy to issue a separate PR that has your commit cherry-picked as well, just let me know.

Hi @C0urante, thank you for the explanation! I'm not sure how to cherry pick my commit onto 1.6.x and force it to fix_timestamp_converter. Would you mind helping me 

> Hi @bingqinzhou--sorry, it looks like the retarget to 1.6.x has brought along all of the commits between 1.6.x and master, which we don't want to merge into master. Instead, we just want to merge your commit. Could you cherry-pick your commit onto 1.6.x, then force-push that branch to your `fix_timestamp_converter` branch?
> 
> If this is too much work I'm happy to issue a separate PR that has your commit cherry-picked as well, just let me know.

Hi @C0urante, I tried the steps as suggested but this branch/PR didn't seem to be updated or different from before, here what I did from my local terminal:

1. check out to 1.6.x branch: `git checkout 1.6.x`
2. cherry pick my commit onto local 1.6.x branch: `git cherry-pick 4cd248c7ca6af5aba34fd6017224c6e1ea20e51d`
3. push local 1.6.x onto remote fix_timestamp_converter: `git push origin fix_timestamp_converter`

After executing steps as above, there's no change or update reflected in this PR, did I miss any steps please?

**Comment by ideasculptor** [comment]
> 
> 1. check out to 1.6.x branch: `git checkout 1.6.x`
> 2. cherry pick my commit onto local 1.6.x branch: `git cherry-pick 4cd248c7ca6af5aba34fd6017224c6e1ea20e51d`
> 3. push local 1.6.x onto remote fix_timestamp_converter: `git push origin fix_timestamp_converter`
> 
> After executing steps as above, there's no change or update reflected in this PR, did I miss any steps please?

Did the push actually succeed?  I'd think you would need to force push that with `git push -f origin fix_timestamp_converter`

**Comment by bingqinzhou** [comment]
> fix_timestamp_converter



> > 1. check out to 1.6.x branch: `git checkout 1.6.x`
> > 2. cherry pick my commit onto local 1.6.x branch: `git cherry-pick 4cd248c7ca6af5aba34fd6017224c6e1ea20e51d`
> > 3. push local 1.6.x onto remote fix_timestamp_converter: `git push origin fix_timestamp_converter`
> > 
> > After executing steps as above, there's no change or update reflected in this PR, did I miss any steps please?
> 
> Did the push actually succeed? I'd think you would need to force push that with `git push -f origin fix_timestamp_converter`

Yes, I was trying to push from `local 1.6.x` to the `original fix_timestamp_converter` the push succeeded, and it didn't require me to force push either. After the push, there was no update in the remote `fix_timestamp_converter` branch tho. Below is how my terminal look like:
Screen Shot 2021-09-03 at 3 41 33 PM

**Comment by C0urante** [comment]
@bingqinzhou I've cherry-picked onto 1.6.x and pushed to a new branch which is used in https://github.com/confluentinc/kafka-connect-bigquery/pull/137. If that looks good to you, we can merge it, propagate the change forward through to master, and put out a new release on the relevant branches.

**Comment by bingqinzhou** [comment]
> @bingqinzhou I've cherry-picked onto 1.6.x and pushed to a new branch which is used in #137. If that looks good to you, we can merge it, propagate the change forward through to master, and put out a new release on the relevant branches.

@C0urante Yes #137 looks good to me. Thank you so much!

**Comment by C0urante** [comment]
Merged this change with https://github.com/confluentinc/kafka-connect-bigquery/pull/137. Thanks for bearing with me @bingqinzhou!

**Comment by bingqinzhou** [comment]
> Merged this change with #137. Thanks for bearing with me @bingqinzhou!

@C0urante Thank you so much for helping me merge this fix!

**Pull request closed without merging**
