### PR TITLE
MINOR: Remove PR template

### PR DESCRIPTION
**Pull request by C0urante**
This template isn't necessary here; we can remove it.

### CODE REVIEW

**Review by cyrusv — COMMENTED** [review]
Why doesn't this apply? My understanding is this is standard across all connectors

**Comment by C0urante** [comment]
It's pretty Confluent-centric and involves some red tape that we shouldn't force on open source community members who've come here after the migration from WePay. We can think about adding a template more fitting for this project at some point down the road but things like "release strategy" and "Does this solution apply anywhere else?" aren't going to be useful for anyone who doesn't work at Confluent and should be removed ASAP.

**Comment by ncliang** [comment]
I've seen the template cause confusion in our other open source repositories as well (JDBC). IMO, there are fields that are still relevant (testing, problem, solution) and fields that we can remove as being not-so-relevant (does this apply anywhere else, release plan). We could just remove those fields that aren't relevant and keep the others (and apply to other open source repos)? WDYT @C0urante

**Comment by cyrusv** [comment]
I see your point that it is geared toward proprietary connectors. I think a good template for open source is great for improving community PR hygiene, so I encourage us to keep some template optimized for community

**Comment by C0urante** [comment]
This template was added when this was a mostly-private fork of an open-source repo, and without being contributed back to that upstream repo. If WePay people like the idea of a template and want to keep it then we can, but otherwise I think it's better to remove it and reduce the friction from the migration process.

**Review by ncliang — APPROVED** [review]
I'm fine with removing to ease the transition while we come up with a general purpose template suitable for our community connectors.

**Comment by C0urante** [comment]
Thanks guys--I've merged this for now and filed https://github.com/confluentinc/kafka-connect-bigquery/issues/30 to keep track of the proposal for a PR template.

**Pull request merged**
