### PR TITLE
Fix MERGE query for tables with columns that have the same name of the table

### PR DESCRIPTION
**Pull request by FreCap**
Adding table in queries to avoid exception such as "UPDATE ... SET does not support updating the entire row at [11:7]"
SQL requires a uniquely identifiable field in queries. If they have the same name, without alias, they are not unique. This fixes the issue

This happens when the table name and a column name have the same name

### CODE REVIEW

**Comment by sagarrao12** [comment]
@FreCap , thanks for this PR. Can you add a more detailed description of the reason behind the fix? And also, can you add a dedicated test for this scenario(i.e table name is the same as col name).

**Comment by FreCap** [comment]
@sagarrao12 
> @FreCap , thanks for this PR. Can you add a more detailed description of the reason behind the fix? 
Modified. Could you please specify what else to add on top of the exception and the fact that SQL requires a clear identifier (in case of conflict in the identifier it throws the exception)?

> And also, can you add a dedicated test for this scenario(i.e table name is the same as col name).
I'm not sure what test could be designed specifically since we are generating plain SQL and never run it. Do you have something in mind?

**Comment by sagarrao12** [comment]
Thanks for updating. It is clearer now.

What I had in mind was an Integration Test where you create a connector against a table having the same name as a column and the connector still doesn't fail. Would it be possible for you to simulate the same?

**Comment by FreCap** [comment]
@sagarrao12 
> What I had in mind was an Integration Test where you create a connector against a table having the same name as a column and the connector still doesn't fail. Would it be possible for you to simulate the same?

It is not possible to test without running the actual query against BQ, do you agree?

**Comment by sagarrao12** [comment]
> @sagarrao12
> 
> > What I had in mind was an Integration Test where you create a connector against a table having the same name as a column and the connector still doesn't fail. Would it be possible for you to simulate the same?
> 
> The BQ SQL engine is the one that parses and throws the exception Hence it is not possible to test without running the actual query against BQ, do you agree? It's one of the pitfalls of query/code templating

hmm I understand the BQ Sql engine is throwing the exception. What I was hinting at is this error still manifests in the connector when the topic results in a bigquery table that has a column with same name as table name. So with this change of yours that shouldn't happen. I was hoping you could add an integration test for the same. Let me know if that makes sense.

**Comment by sagarrao12** [comment]
@FreCap , I meant writing an integration test with the conditions meeting. Anyways, I looked at the changes again and we don't need to block on IT for this. I will check internally on having the Jenkins build running successfully before merging this. Thanks for your work on this.

**Comment by FreCap** [comment]
@sagarrao12 appreciated.

> I will check internally on having the Jenkins build running successfully before merging this. Thanks for your work on this.
I created a Jenkins like job for github: 
https://github.com/FreCap/kafka-connect-bigquery/blob/master-accepting-MR/.github/workflows/build.yml
This could make it easier, could we please check this in as well?

**Review by sagarrao12 — APPROVED** [review]
LGTM

**Comment by sagarrao12** [comment]
> @sagarrao12 appreciated.
> 
> > I will check internally on having the Jenkins build running successfully before merging this. Thanks for your work on this.
> > I created a Jenkins like job for github:
> 
> https://github.com/FreCap/kafka-connect-bigquery/blob/master-accepting-MR/.github/workflows/build.yml This could make it easier, could we please check this in as well?

Oh. That won't be possible for us to merge. I was able to run the build against this PR and the tests have passed. Also, can you create the PR against 2.4.x branch so that this can be released as a bugfix? Thanks!

**Pull request merged**
