### PR TITLE
Time partitioning

### PR DESCRIPTION
**Pull request by mubeen**
Upgrading of the google cloud version and its related libraries to bring in the additional time partitioning types support for MONTH and YEAR. Implemented code changes for the MONTH and YEAR time partitioning types.

### CODE REVIEW

**Comment by C0urante** [comment]
Hi @mubeen, thanks for the PR. I won't be able to look at it this week but can set some time out next week on Tuesday or Wednesday.

As a preliminary note, this should target `master` since it's a new feature; we only target feature branches such as `1.6.x` or `2.0.x` for bug fixes.

**Comment by mubeen** [comment]
Thanks @C0urante, we are currently using version 1.6.6 which is the latest on confluent hub for our production environment. We require this feature to be available to us via confluent hub as soon as possible, should I still create the pull request against master and how would that filter through to us?

**Comment by C0urante** [comment]
Yeah, you should still create the PR against master. I'll see about getting the ball rolling on a 2.0.0 release, which wouldn't include this feature but is also necessary if we want to put out a 2.1.0 release, which would include this feature (as long as it's merged in time).

There's some substantial docs work that needs to be done to note the differences between 1.6.x and 2.0.x; once that's out of the way, performing an actual release shouldn't be too difficult. Can't make any promises about a timeline but will keep you in the loop if/when I know more.

**Comment by mubeen** [comment]
Closing pull request, new pull requested created against master for this change.

**Pull request closed without merging**
