### PR TITLE
Kafka Connect BigQuery issue 87

### PR DESCRIPTION
**Pull request by jmcp**

### CODE REVIEW

**Comment by jmcp** [comment]
I was unable to successfully run all of the integration tests. Three failures occurred:

```
[ERROR] Errors:
[ERROR]   UpsertDeleteBigQuerySinkConnectorIT.testDelete:210->BaseConnectorIT.waitForCommittedRecords:155->BaseConnectorIT.waitForCommittedRecords:161->BaseConnectorIT.lambda$waitForCommittedRecords$1:173 » NoRetry
[ERROR]   UpsertDeleteBigQuerySinkConnectorIT.testUpsert:154->BaseConnectorIT.waitForCommittedRecords:155->BaseConnectorIT.waitForCommittedRecords:161->BaseConnectorIT.lambda$waitForCommittedRecords$1:173 » NoRetry
[ERROR]   UpsertDeleteBigQuerySinkConnectorIT.testUpsertDelete:269->BaseConnectorIT.waitForCommittedRecords:155->BaseConnectorIT.waitForCommittedRecords:161->BaseConnectorIT.lambda$waitForCommittedRecords$1:173 » NoRetry
[INFO]
[ERROR] Tests run: 5, Failures: 0, Errors: 3, Skipped: 1
[INFO]
```

Suggestions on how to resolve these will be gratefully received.

**Comment by C0urante** [comment]
@jmcp Based on the discussion on #87 I was under the impression that this PR would be strictly logging changes. However, it looks like there are actual functional changes being proposed here, including dependency version bumps and a new config property. Before proceeding further with review, I'd like it if we could get a complete description of the proposed changes and the motivation for them either in the description for this PR or in #87, to best understand your use case and whether this approach makes sense not just for you, but for users of the connector in general.

As far as the CI build goes, there's a few known flaky integration tests for the upsert/delete logic, so I wouldn't worry too much about whether Jenkins gives us an ❌ or a ✅. As long as you can build the project locally and the tests pass it should be alright.

If you have trouble getting tests to pass locally, the best advice I can provide is to review the logs for errors and go from there. I've also had some success with step-by-step debugging in my IDE, but that's a bit of an extreme option and I usually only resort to it after I feel I've exhausted all of the information provided to me by the test logs.

**Comment by jmcp** [comment]
@C0urante  I'll answer your questions here:

* The dependency version bumps are so that we can get more debugging info from BigQuery - the methods I wanted were not available in the earlier version that the connector currently depends upon. The `table.getIAMResourceName()` call enabled us to determine that we were missing permissions in GCP.
* The new config property is something that I added to assist my developers with determining where their schema was broken. It's disabled by default. 
* I'll have another go at the failing integration tests

**Comment by C0urante** [comment]
TRACE-level logging seems like a pretty roundabout way to let people know that they lack GCP permissions for a table the connector is touching. Did you not see any other error messages in the logs already when that happened? Ideally we'd be able to surface this info by failing the task and including a message about the cause of the failure in the stack trace exposed in the Connect REST API.

As far as `ignoreInvalidFields` goes, I don't think it's a useful long-term approach for the goal it seeks to accomplish. [KIP-610](https://cwiki.apache.org/confluence/display/KAFKA/KIP-610%3A+Error+Reporting+in+Sink+Connectors) introduced a mechanism that sink connectors can use to handle bad data; it'd be better to implement this in the connector so that users can choose not only whether to tolerate bad data, but also optionally log it and/or produce it back to a dead letter queue topic.

Oh, and just out of curiosity, what version of the connector are you running right now? It's possible there have been usability improvements in later releases that might make things like understanding the cause of connector failure easier.

**Comment by jmcp** [comment]
> TRACE-level logging seems like a pretty roundabout way to let people know that they lack GCP permissions for a table the connector is touching. Did you not see any other error messages in the logs already when that happened? Ideally we'd be able to surface this info by failing the task and including a message about the cause of the failure in the stack trace exposed in the Connect REST API.

You're right, that should be a WARN (tbf I went through and redid most of the logger calls as TRACE). The errors that we observed were 

```com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Failed to create table ```

Funneling all of the possible error responses into a BigQueryConnectException without any extra logging was a significant impediment to getting this connector up and working in our environment. 

 
> As far as `ignoreInvalidFields` goes, I don't think it's a useful long-term approach for the goal it seeks to accomplish. [KIP-610](https://cwiki.apache.org/confluence/display/KAFKA/KIP-610%3A+Error+Reporting+in+Sink+Connectors) introduced a mechanism that sink connectors can use to handle bad data; it'd be better to implement this in the connector so that users can choose not only whether to tolerate bad data, but also optionally log it and/or produce it back to a dead letter queue topic.

Yes, [KIP-610](https://cwiki.apache.org/confluence/display/KAFKA/KIP-610%3A+Error+Reporting+in+Sink+Connectors)  looks much better.  I'd much prefer to have that mechanism instead. I'll remove `ignoreInvalidFields`.


> Oh, and just out of curiosity, what version of the connector are you running right now? It's possible there have been usability improvements in later releases that might make things like understanding the cause of connector failure easier.

I've been building and using the current trunk.

**Comment by C0urante** [comment]
> Funneling all of the possible error responses into a BigQueryConnectException without any extra logging was a significant impediment to getting this connector up and working in our environment.

Do you think it might be more useful to improve the failure messages that the connector displays in the Connect REST API rather than add more-extensive logging? I'm not opposed to better logging and a lot of the changes here seem good, it just seems like it might be more convenient for you and other users to not have to read logs to begin with. For example, would it help if we included the "reason", "location", and "message" information from `BigQueryError`s?

> Yes, KIP-610 looks much better. I'd much prefer to have that mechanism instead. I'll remove `ignoreInvalidFields`.

Great, thanks! I believe it's on our roadmap to add the KIP-610 error reporting mechanism to this connector but I don't have a firm timeline of that yet. If you're interested in seeing that sooner rather than later, feel free to open a separate issue and we can discuss some of the design aspects to it (I'm thinking this may be fairly involved as we'll have to be pretty thorough about which types of errors we use the error reporting mechanism for and which ones we fail the connector on unconditionally).

> I've been building and using the current trunk.

Cool, thanks for confirming 👍

**Comment by jmcp** [comment]
> > Funneling all of the possible error responses into a BigQueryConnectException without any extra logging was a significant impediment to getting this connector up and working in our environment.
> 
> Do you think it might be more useful to improve the failure messages that the connector displays in the Connect REST API rather than add more-extensive logging? I'm not opposed to better logging and a lot of the changes here seem good, it just seems like it might be more convenient for you and other users to not have to read logs to begin with. For example, would it help if we included the "reason", "location", and "message" information from `BigQueryError`s?

Putting my non-developer hat on, I think it would be considerably nicer to have these information surfaced in the REST API. I've filed an enhancement request for the timestamp case already  https://issues.apache.org/jira/browse/KAFKA-12425.


> > Yes, KIP-610 looks much better. I'd much prefer to have that mechanism instead. I'll remove `ignoreInvalidFields`.
> 
> Great, thanks! I believe it's on our roadmap to add the KIP-610 error reporting mechanism to this connector but I don't have a firm timeline of that yet. If you're interested in seeing that sooner rather than later, feel free to open a separate issue and we can discuss some of the design aspects to it (I'm thinking this may be fairly involved as we'll have to be pretty thorough about which types of errors we use the error reporting mechanism for and which ones we fail the connector on unconditionally).

Filed issue 102.

**Comment by jmcp** [comment]
Ping @C0urante - it's been three weeks since there was any comment on my PR. If you're too busy could you please help me find another project committer to work with on this PR please.

**Review by C0urante — COMMENTED** [review]
Thanks for the ping @jmcp. There's still a lot that needs to be cleaned up here; I've left some initial comments.

Please ping me directly and let me know when you believe this is ready for another round of review; I'll try to respond within a few days of that time.

**Comment by C0urante** [comment]
Closing due to lack of activity; @jmcp feel free to open if you would like to resume work on this.

**Pull request closed without merging**
