### PR TITLE
Support n:1 to topic2TableMap (topic:table)

### PR DESCRIPTION
**Pull request by jx2lee**
like snowflow sink connector, it would be nice to have this.
[https://github.com/snowflakedb/snowflake-kafka-connector/pull/459](https://github.com/snowflakedb/snowflake-kafka-connector/pull/459)

I haven't written an integration test code because integration tests don't work well locally. Do I need to?

### CODE REVIEW

**Comment by jx2lee** [comment]
please review my PR, @ maintainers

**Review by b-goyal — COMMENTED** [review]
Thanks for the PR @jx2lee . The changes look fine. Let me run the jenkins job to validate no ITs break.

**Comment by jx2lee** [comment]
@b-goyal thanks for check PR!

**Comment by b-goyal** [comment]
@jx2lee - build passes, good to merge. Could you please rebase the branch to 2.5.x (instead of master) ?

**Comment by jx2lee** [comment]
@b-goyal success to chnage root branch (master to 2.5.x) check this out, please/

**Comment by b-goyal** [comment]
Modified the PR base branch to 2.5.x as well. @jx2lee

**Comment by jx2lee** [comment]
omg, i missed that. thanks, @b-goyal

**Comment by jx2lee** [comment]
Jenkins workflow was failed. could you check this out? @b-goyal

**Comment by b-goyal** [comment]
Jenkins build is failing, re-tried a few times. I will take a look into it and approve the PR once this build is fixed.

**Comment by jx2lee** [comment]
okay, i got it. thanks for pr-review

**Comment by jx2lee** [comment]
@b-goyal could you tell me how long failed build will be fixed?

**Comment by b-goyal** [comment]
Hey @jx2lee, was out for a few days. I will check and get back on this by next week.

**Review by b-goyal — APPROVED** [review]

**Pull request merged**
