### PR TITLE
Update docs URL path

### PR DESCRIPTION
**Pull request by tikimims**
## Problem

- Update docs URL path to exact path (currently its redirecting but we're updating now to have a clean trail)
- Please let me know if I should target a different branch for this one and will do if needed.

## Solution
- Update docs URL path to exact path

### CODE REVIEW

**Comment by tikimims** [comment]
@confluentinc/connect-team2 Can I get +1 on this PR? Thanks so much!

cc @joel-hamill @NathanNam

**Comment by C0urante** [comment]
@tikimims can we target an earlier branch, like 1.2.x?

**Comment by tikimims** [comment]
@C0urante Retargeted to 1.2.x 👍

**Review by C0urante — APPROVED** [review]
LGTM

**Comment by tikimims** [comment]
@C0urante Looks I can't merge on this one either. Sorry about that. It's a different type of message though this time around. It's speaking of protected branches.

**Comment by C0urante** [comment]
Weird, oh well. I merged it.

**Comment by tikimims** [comment]
💯 Thank you!!

**Pull request merged**
